# generate_full_ai_report.py
# 作用：一键生成完整 PDF 报告（自动分析 + 生成图表 + 模型评估 + 结论）
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, roc_auc_score, roc_curve

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle

# ---------------- 基础准备 ----------------
base = Path(".").resolve()
csv_path = base / "sales_100.csv"
assert csv_path.exists(), "未找到 sales_100.csv，请确保脚本与 CSV 在同一文件夹"

df = pd.read_csv(csv_path)

# 日期字段处理
df["date"] = pd.to_datetime(df["date"])
df["day_of_week"] = df["date"].dt.day_name()

# ---------------- 常规分析与图表 ----------------
# 城市收入
city_rev = df.groupby("city")["total"].sum().reset_index().sort_values("total", ascending=False)
plt.bar(city_rev["city"], city_rev["total"])
plt.title("Total Revenue by City"); plt.xlabel("City"); plt.ylabel("Revenue"); plt.tight_layout()
plt.savefig("city_revenue_chart.png"); plt.close()

# 品类收入（横向）
pl_rev = df.groupby("product_line")["total"].sum().reset_index().sort_values("total")
plt.barh(pl_rev["product_line"], pl_rev["total"])
plt.title("Total Revenue by Product Line"); plt.xlabel("Revenue"); plt.ylabel("Product Line"); plt.tight_layout()
plt.savefig("product_revenue_chart.png"); plt.close()

# 性别收入
gender_rev = df.groupby("gender")["total"].sum().reset_index().sort_values("total", ascending=False)
plt.bar(gender_rev["gender"], gender_rev["total"])
plt.title("Total Revenue by Gender"); plt.xlabel("Gender"); plt.ylabel("Revenue"); plt.tight_layout()
plt.savefig("gender_revenue_chart.png"); plt.close()

# 支付方式收入
pay_rev = df.groupby("payment")["total"].sum().reset_index().sort_values("total", ascending=False)
plt.bar(pay_rev["payment"], pay_rev["total"])
plt.title("Total Revenue by Payment Method"); plt.xlabel("Payment"); plt.ylabel("Revenue"); plt.tight_layout()
plt.savefig("payment_revenue_chart.png"); plt.close()

# KPI
top_city, top_city_val = city_rev.iloc[0]["city"], float(city_rev.iloc[0]["total"])
top_pl, top_pl_val = pl_rev.iloc[-1]["product_line"], float(pl_rev.iloc[-1]["total"])
top_gender, top_gender_val = gender_rev.iloc[0]["gender"], float(gender_rev.iloc[0]["total"])
top_pay, top_pay_val = pay_rev.iloc[0]["payment"], float(pay_rev.iloc[0]["total"])
total_revenue = float(df["total"].sum())
row_count = int(len(df))
avg_unit_price = float(df["unit_price"].mean())
avg_quantity = float(df["quantity"].mean())

# ---------------- 逻辑回归模型：预测高消费 ----------------
threshold = df["total"].median()
df["high_spender"] = (df["total"] >= threshold).astype(int)

num_features = ["unit_price", "quantity"]
cat_features = ["product_line", "city", "customer_type", "gender", "payment", "day_of_week"]

X = df[num_features + cat_features]
y = df["high_spender"]

ct = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_features),
        ("num", "passthrough", num_features),
    ]
)

clf = Pipeline(steps=[
    ("prep", ct),
    ("model", LogisticRegression(max_iter=1000))
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_proba = clf.predict_proba(X_test)[:, 1]

report = classification_report(y_test, y_pred, output_dict=True)
acc = report["accuracy"]
prec_1 = report["1"]["precision"]
rec_1 = report["1"]["recall"]
f1_1 = report["1"]["f1-score"]
roc = roc_auc_score(y_test, y_proba)

# ROC 曲线图
fpr, tpr, _ = roc_curve(y_test, y_proba)
plt.plot(fpr, tpr, label=f"ROC-AUC = {roc:.3f}")
plt.plot([0,1],[0,1], linestyle="--")
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("ROC Curve - High Spender Classification")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("roc_curve.png"); plt.close()

# ---------------- 生成 PDF 报告 ----------------
pdf_path = base / "sales_report_ai_version.pdf"
c = canvas.Canvas(str(pdf_path), pagesize=letter)
w, h = letter

# 封面
c.setFont("Helvetica-Bold", 22)
c.drawString(70, h-80, "Sales Data Analysis Report (AI Version)")
c.setFont("Helvetica", 12)
c.drawString(70, h-105, "Source: sales_100.csv | Auto-generated by Python")
c.drawString(70, h-120, "Includes KPIs, charts, ML model metrics, and business insights")

# KPI 表格
kpi_data = [
    ["Metric", "Value"],
    ["Top City (Revenue)", f"{top_city}  |  {top_city_val:,.2f}"],
    ["Top Product Line",   f"{top_pl}  |  {top_pl_val:,.2f}"],
    ["Top Gender",         f"{top_gender}  |  {top_gender_val:,.2f}"],
    ["Top Payment",        f"{top_pay}  |  {top_pay_val:,.2f}"],
    ["Total Revenue",      f"{total_revenue:,.2f}"],
    ["Rows",               f"{row_count}"],
    ["Avg Unit Price",     f"{avg_unit_price:.2f}"],
    ["Avg Quantity",       f"{avg_quantity:.2f}"],
]
table = Table(kpi_data, colWidths=[160, 360])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTSIZE", (0,0), (-1,-1), 10),
    ("ALIGN", (0,0), (-1,-1), "LEFT"),
]))
table.wrapOn(c, 70, h-320)
table.drawOn(c, 70, h-360)

# 模型指标表
model_data = [
    ["Model Metric", "Value"],
    ["Accuracy", f"{acc:.3f}"],
    ["Precision (High)", f"{prec_1:.3f}"],
    ["Recall (High)", f"{rec_1:.3f}"],
    ["F1 (High)", f"{f1_1:.3f}"],
    ["ROC-AUC", f"{roc:.3f}"],
]
table2 = Table(model_data, colWidths=[160, 360])
table2.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("FONTSIZE", (0,0), (-1,-1), 10),
    ("ALIGN", (0,0), (-1,-1), "LEFT"),
]))
table2.wrapOn(c, 70, h-520)
table2.drawOn(c, 70, h-560)

# Highlights
c.setFont("Helvetica-Bold", 14); c.drawString(70, 120, "Highlights & Actions")
c.setFont("Helvetica", 11)
c.drawString(70, 100, f"• Top city: {top_city} ({top_city_val:,.2f}); focus inventory & local promos.")
c.drawString(70, 85,  f"• Best product line: {top_pl} ({top_pl_val:,.2f}); prioritize merchandising & margins.")
c.drawString(70, 70,  f"• Gender: {top_gender} spends more; tailor campaigns to audience segment.")
c.drawString(70, 55,  f"• Payment: {top_pay} leads; consider bank/e-wallet partnerships.")
c.drawString(70, 40,  f"• ML model ROC-AUC {roc:.3f}; use predictions to target high-value orders.")

c.showPage()

# 第二页：四张业务图
c.setFont("Helvetica-Bold", 16)
c.drawString(70, h-60, "Business Charts")

images = [
    ("city_revenue_chart.png", "Total Revenue by City"),
    ("product_revenue_chart.png", "Total Revenue by Product Line"),
    ("gender_revenue_chart.png", "Total Revenue by Gender"),
    ("payment_revenue_chart.png", "Total Revenue by Payment Method"),
]
y = h-100
for path, caption in images:
    p = base / path
    c.setFont("Helvetica-Bold", 12); c.drawString(70, y, caption)
    y -= 12
    if p.exists():
        c.drawImage(str(p), 70, y-170, width=470, height=170, preserveAspectRatio=True, anchor='n')
        y -= 190
    else:
        c.setFont("Helvetica", 11); c.drawString(70, y-12, f"(Missing: {path})"); y -= 40

c.showPage()

# 第三页：ROC 曲线
c.setFont("Helvetica-Bold", 16)
c.drawString(70, h-60, "Model ROC Curve")
roc_img = base / "roc_curve.png"
if roc_img.exists():
    c.drawImage(str(roc_img), 70, h-420, width=470, height=340, preserveAspectRatio=True)
else:
    c.setFont("Helvetica", 12); c.drawString(70, h-80, "(Missing: roc_curve.png)")

# 结束
c.showPage()
c.save()
print(f"[SUCCESS] PDF 生成完成：{pdf_path}")
